// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsfU8lK3ZWSlW08yaWaeh2tI6-6poctMQ',
    appId: '1:112541665833:web:808b635d39bd375ca9aa38',
    messagingSenderId: '112541665833',
    projectId: 'g-summits',
    authDomain: 'g-summits.firebaseapp.com',
    storageBucket: 'g-summits.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfwTjih7zkIoHGJYnvvDz0Yyo-732bAEs',
    appId: '1:112541665833:android:234437b80fa291a4a9aa38',
    messagingSenderId: '112541665833',
    projectId: 'g-summits',
    storageBucket: 'g-summits.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXQh6Yt1l7NLIT4pVc2WrAaF_qoMjuL9s',
    appId: '1:112541665833:ios:7c6f7e7cdf1531cba9aa38',
    messagingSenderId: '112541665833',
    projectId: 'g-summits',
    storageBucket: 'g-summits.appspot.com',
    iosClientId: '112541665833-hrre32v6s4l99tjb926tmfdh565bofqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
